"""
Streamlit dashboard for the Biomass Waste-to-Energy (WtE) Decision
Framework.

Lets a reviewer interactively explore the final hybrid conversion-
technology decisions (Phase 4C) without running the notebook pipeline:
filter by biomass class / fuel cluster, inspect technology
distributions, and compare a sample's key decision-active features
against its assigned cluster.

Run locally with:
    streamlit run app.py
"""

import pandas as pd
import streamlit as st

st.set_page_config(page_title="Biomass WtE Decision Framework", layout="wide")

DATA_PATH = "data/processed/comparison_decisions.csv"


@st.cache_data
def load_data(path: str) -> pd.DataFrame:
    return pd.read_csv(path)


st.title("🔥 Biomass Waste-to-Energy (WtE) Decision Framework")
st.caption(
    "Interactive explorer for cluster-informed thermochemical conversion "
    "technology decisions across 135 Australian biomass and waste fuel samples."
)

try:
    df = load_data(DATA_PATH)
except FileNotFoundError:
    st.error(
        f"Could not find `{DATA_PATH}`. Run the notebooks in order "
        "(01 → 06a) first, or check that you launched the app from the "
        "repository root."
    )
    st.stop()

# --- Sidebar filters --------------------------------------------------------
st.sidebar.header("Filters")

classes = sorted(df["Class"].dropna().unique().tolist())
selected_classes = st.sidebar.multiselect("Biomass Class", classes, default=classes)

clusters = sorted(df["Cluster"].dropna().unique().tolist())
selected_clusters = st.sidebar.multiselect(
    "Fuel Cluster", clusters, default=clusters, format_func=lambda c: f"Cluster {int(c)}"
)

filtered = df[df["Class"].isin(selected_classes) & df["Cluster"].isin(selected_clusters)]

st.sidebar.metric("Samples matching filters", len(filtered))

# --- Overview metrics --------------------------------------------------------
col1, col2, col3, col4 = st.columns(4)
col1.metric("Total Samples", len(df))
col2.metric("Filtered Samples", len(filtered))
col3.metric("Fuel Clusters", df["Cluster"].nunique())
col4.metric(
    "Technologies Recommended",
    filtered["Final_Conversion_Technology"].nunique() if len(filtered) else 0,
)

st.divider()

# --- Technology distribution --------------------------------------------------------
left, right = st.columns(2)

with left:
    st.subheader("Final (Hybrid) Technology Distribution")
    st.bar_chart(filtered["Final_Conversion_Technology"].value_counts())

with right:
    st.subheader("Cluster vs. Final Technology")
    if len(filtered):
        st.dataframe(
            pd.crosstab(filtered["Cluster"], filtered["Final_Conversion_Technology"]),
            use_container_width=True,
        )
    else:
        st.info("No samples match the current filters.")

st.divider()

# --- Decision framework comparison --------------------------------------------------------
st.subheader("Decision Framework Comparison (Cluster-only vs. Rule-only vs. Hybrid)")
comparison_cols = [
    "Sample_ID", "Biomass_Type", "Class", "Cluster",
    "Final_Tech_ClusterOnly", "Final_Tech_RuleOnly", "Final_Conversion_Technology",
    "Constraint_Level",
]
available_cols = [c for c in comparison_cols if c in filtered.columns]
st.dataframe(filtered[available_cols], use_container_width=True, height=350)

# --- Key feature inspection --------------------------------------------------------
st.subheader("Decision-Active Feature Profile")
key_features = [
    "Ash_db", "VM_db", "FC_db", "Moist_ar",
    "Alkali_Index", "Silica_Ratio", "Base_Acid_Ratio",
    "Energy_Density_Index", "Combustibility_Index",
]
available_features = [f for f in key_features if f in filtered.columns]

if len(filtered) and available_features:
    st.dataframe(
        filtered.groupby("Final_Conversion_Technology")[available_features]
        .mean()
        .round(2),
        use_container_width=True,
    )
else:
    st.info("No samples available for feature profiling under the current filters.")

st.caption(
    "Source: `data/processed/comparison_decisions.csv`, generated by "
    "notebooks 01 through 06. See the project README for full methodology."
)
